---
title: "data_processing_pipeline"
output: html_document
---

# Pipeline 

In this file functional pipeline: raw -> processed data 

```{r setup}
library(dplyr)
library(stringr)

data = read.csv("data/translation_data_possible_duplicates.csv")
new_names = read.csv('data/translated_names.csv')

data_eng <- data
colnames(data_eng) <- new_names$x
```



# translation of variable names 

```{r, eval=F}
# translated names 

translated_names <- c(
  'teaviku_laad'="publication_type",
  'sihtrühm'="target_audience", 
  'pealkiri'="title",
  'autor'="author",
  'originaal_pealkiri'="title_original",
  'Žanr'="genre",
  'tõlkija'="translator", 
  'lähtekeel'="source_language", 
  'lähtekirjandus'="source_literature",
  'toimetaja'="editor",
  'ees__järelsõna_autor'="fore_afterword_author",
  'ilmumiskoht'="publication_location",
  'kirjastaja'="publisher", 
  'ilmumisaasta'="publication_year", 
  'füüsiline_kirjeldus'="physical_description", 
  'trükikordus'="edition", 
  'sarjaandmed'="series", 
  'arvustatava_tõlkeraamatu_autor'="author_of_translated_book_under_review_to_be_removed", 
  'väljaanne'="issue", 
  'number_leheküljed'="n_pages", 
  'sisu'="content", 
  'märkused'="notes", 
  'id'="id") 

write.csv(translated_names, 'data/translated_names.csv')
```


