services:
  db:
    image: postgres:alpine3.22
    # restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=translation_db
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/:z
      - ${PWD}/db/create_db.sql:/docker-entrypoint-initdb.d/create_tables.sql:z
      - ${PWD}/db/traditional_view.sql:/docker-entrypoint-initdb.d/create_views.sql:z
    healthcheck:
      test: pg_isready -U dbuser -d translation_db
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    image: translation/api
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ${PWD}/run.sh:/app/run.sh:z
      - ${PWD}/src:/app/src:z
      - ${PWD}/../data/clean_for_sql:/app/data:z
    env_file:
      - .env
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
