---
title: "data-exploration"
output: html_document
---

```{r}
library(dplyr)
library(stringr)

data = read.csv("translation_data_possible_duplicates.csv")
```

book being part of one series at a time 
one target audience
review one book at a time 
one source lang, literature
not one pub loc 

scrape birth year 


```{r}
data[duplicated(data),] |> nrow()
```

```{r}
translated_names <- c(
  'teaviku_laad'="publication_type",
  'sihtrühm'="target_audience", 
  'pealkiri'="title",
  'autor'="author",
  'originaal_pealkiri'="title_original",
  'Žanr'="genre",
  'tõlkija'="translator", 
  'lähtekeel'="source_language", 
  'lähtekirjandus'="source_literature",
  'toimetaja'="editor",
  'ees__järelsõna_autor'="comment_author",
  'ilmumiskoht'="publisher_location",
  'kirjastaja'="publisher", 
  'ilmumisaasta'="publication_year", 
  'füüsiline_kirjeldus'="physical_description", 
  'trükikordus'="print_number", 
  'sarjaandmed'="series", 
  'arvustatava_tõlkeraamatu_autor'="author_of_translated_book_under_review_to_be_removed", 
  'väljaanne'="issue", 
  'number_leheküljed'="n_pages", 
  'sisu'="content", 
  'märkused'="notes", 
  'id'="id") 

write.csv(translated_names, 'translated_names.csv')

#Translated with DeepL.com (free version)

data_ed <- data
names(data_ed) <- translated_names
```

```{r}
data_eng |> select(series_information) |> unique()
```



```{r}
# search also for those who are not expected to have ',' 
data_ed |> filter_all(any_vars(str_detect(., ';'))) |> View()

data_ed |> filter(str_detect(title, ';'))
data_ed |> filter(str_detect(title, ',')) |> View()

# data_ed |> select(edition_1,edition_2) |> unique() |> View()

# data_ed |> filter(across(.fns = all(), str_detect(";")))
```

Variables with ',' indicating two or more records: 
- source language 
- source literature 
- genre

```{r}
data_ed |> filter(str_detect(source_language, ','))
data_ed |> filter(str_detect(source_literature, ','))
data_ed |> filter(str_detect(genre, ','))

data_ed |> View()
```

```{r}
data |> group_by(sihtrühm) |> count() 
```


```{r}
data |> group_by(teaviku_laad) |> count() 
```

```{r}
data |> group_by(autor) |> count()
```

perhaps good to remember 
```
(Schnübbe-) Schomburgk, Helene	1		
(Schnübbe-)Schomburgk, Helene; Faber, K.
```


```{r}
all_authors <- data$autor |> unique()
# all_authors[str_detect(all_authors,';')] # more authors in one record 
all_authors[str_detect(all_authors,'[0-9]')] # random
all_authors[str_detect(all_authors,'[0-9]') & !str_detect(all_authors,'[A-Z]') & !str_detect(all_authors,'[a-z]')]
all_authors[!str_detect(all_authors,'[0-9]')]
all_authors[str_length(all_authors) < 6]
all_authors[str_detect(all_authors,"-")]
all_authors[str_detect(all_authors,"\\(")]
all_authors[str_detect(all_authors,"\\[")]
all_authors[str_detect(all_authors,"\\?")]

#summary: 

#  weird things when auth < 6 
#  more authors when ; 
#  rather practical years
#  pseud
all_authors[str_length(all_authors) < 4 & str_detect(all_authors,"\\.")]
all_authors[str_length(all_authors) < 4 & str_detect(all_authors,"-")]
```


```{r}
data_ed |> filter(str_length(author) < 6) |> View()
data_ed |> filter(str_detect(title, 'Raamatu kohta')) # data can be taken from the sq brackets []
```

```{r}
data_ed |> colnames()
data_ed |> filter()
```


```{r}
data_ed |> 
```


```{r}
length(data$id |> unique())
data |> nrow()
```

```{r}
library(ggplot2)
data |>  
  ggplot(aes(x=ilmumisaasta)) + geom_histogram()
```

