---
title: "data-exploration"
output: html_document
---

```{r}
library(stringr)
library(ggplot2)
library(dplyr)
library(knitr)
library(tidyr)

```



```{r}
data = read.csv("translation_data_possible_duplicates.csv")
```

```{r}
data[duplicated(data),]
```

```{r}
colnames(data)
```

```{r}
unique(data$teaviku_laad)
unique(data$sihtrühm)
unique(data$Žanr)
unique(data$lähtekeel)
#unique(data$lähtekirjandus)
#unique(data$toimetaja)
#unique(data$ilmumiskoht)
#unique(data$kirjastaja)
#unique(data$füüsiline_kirjeldus)
#unique(data$sarjaandmed)
#unique(data$number_leheküljed)
#unique(data$märkused)

# 1 to n: 1 book can have multiple publication types
publication_type_translations = c('Tõlkearvustus' = 'Review of translation',
  'Perioodikas ilmunud tõlge' = 'Translation published in periodicals',
  'Tõlkeraamat' = 'Book translation',
  'Kogumikus ilmunud tõlge' = 'Translation published in miscellanea')


```

```{r}
unique(data$lähtekeel)

```


```{r}
data %>% filter(strlähtekeel == "vene, saksa, prantsuse") %>% View()
data %>% filter(strlähtekeel == "vene, saksa, prantsuse") %>% View()
```
```{r}
data %>% filter(str_detect(pealkiri, ";")) %>% View()

```


```{r}
max(nchar(data$autor))

data %>% filter(nchar(autor) == 254)
```


book being part of one series at a time
book having one target audience
review one book at a time
one source lang, literature
not one pub loc



```{r}
data %>% filter(str_detect(pealkiri, ";")) %>% filter(str_detect(lähtekeel, ";")) %>% View()

```






